In [1]:
!pip install selenium

WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/opencv_python-4.10.0.84.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/tensorflow_io_gcs_filesystem-0.37.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/opencv_python-4.10.0.84.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/tensorflow_io_gcs_filesystem-0.37.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/opencv_python_headless-4.10.0.84.dist-info due to invalid metadata entry 'name'
Requirement already satisfied: selenium in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from selenium) (4.11.0)
Requirement already satisfied: attrs>=23.2.0 in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Users/lasyatummala/anaconda3/lib/python3.11/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/opencv_python-4.10.0.84.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/tensorflow_io_gcs_filesystem-0.37.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/opencv_python_headless-4.10.0.84.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/opencv_python-4.10.0.84.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/tensorflow_io_gcs_filesystem-0.37.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/opencv_python-4.10.0.84.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/tensorflow_io_gcs_filesystem-0.37.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/opencv_python-4.10.0.84.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /Users/lasyatummala/anaconda3/lib/python3.11/site-packages/tensorflow_io_gcs_filesystem-0.37.1.dist-info due to invalid metadata entry 'name'

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from bs4 import BeautifulSoup
import requests
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import selenium

In [3]:
url = 'https://www.eenadu.net/business/latest-news'

In [4]:
response = requests.get(url)
print(response)

<Response [200]>

In [5]:
soup = BeautifulSoup(response.text, 'html.parser')

In [6]:
# Extract all news articles
articles = soup.find_all("div", class_="thumb-description")

# List to store descriptions
descriptions = []

# Loop through each news article
for article in articles:
    # Extract description (within <br> tags)
    description_parts = []
    for br in article.find_all("br"):
        if br.next_sibling and isinstance(br.next_sibling, str):
            description_parts.append(br.next_sibling.strip())

    description_text = " ".join(description_parts)
    descriptions.append(description_text if description_text else "N/A")

# Create a DataFrame with only the 'Description' column
df = pd.DataFrame({"Description": descriptions})

# Display the DataFrame
print(df)

                                          Description
0                                                 N/A
1                                                 N/A
2                                                 N/A
3                                                 N/A
4                                                 N/A
5                                                 N/A
6                                                 N/A
7                                                 N/A
8                                                 N/A
9                                                 N/A
10                                                N/A
11                                                N/A
12  ఆర్థిక లక్ష్యాలను సాధించడం ఒక్క రోజులో అయ్యే ప...
13  సొంతిల్లు.. అందరి కల. గృహరుణం వడ్డీ రేట్లు కాస...
14  తల్లిదండ్రులందరూ పిల్లలకు మంచి ఆర్థిక భవిష్యత్...
15  అంతా సాఫీగా సాగిపోతుంది అనుకున్న క్షణంలోనే ఎదో...
16  వచ్చే మూడేళ్లలో (2028 కల్లా) ప్రపంచంలోనే మూడో ...
17  త్వరలోనే పదవీ విరమణ చేయబోతున్నాను. ఇప్పుడు నేన...
18  జెన్‌ ఏఐ (జెనరేటివ్‌ కృత్రిమమేధ)తో మనదేశంలో 20...
19  హెచ్‌డీఎఫ్‌సీ మ్యూచువల్‌ ఫండ్‌ ఒక ఇండెక్స్‌ పథ...
20  దేశీయ స్నాక్స్, మిఠాయిల కంపెనీ హల్దీరామ్‌ స్నా...
21  ఓలా ఎలక్ట్రిక్, హోలీ సందర్భంగా ఫ్లాష్‌ సేల్‌ ప...
22  ఒక కంపెనీ షేరు ధరలను ప్రభావితం చేసే సమాచారం (య...
23  దేశీయంగా ప్రయాణికుల వాహన (కార్లు, ఎస్‌యూవీ, వ్...
24  సూచీలు వరుసగా అయిదో రోజూ నష్టాలపాలయ్యాయి. స్థి...
25  ప్రస్తుత ఆర్థిక సంవత్సరం ఏప్రిల్‌- డిసెంబరులో ...
26  అమెరికా మార్కెట్లో విడుదల చేసిన ఒక ఔషధం బ్యాచ్...
27  పర్యావరణ మార్పు వల్ల జరిగే ప్రమాదాలు, నష్టాలు,...
28  మాగ్మా జనరల్‌ ఇన్సూరెన్స్‌ను బాబా రామ్‌దేవ్‌ న...
29  అమెరికా ఆంక్షల నేపథ్యంలో రష్యా నుంచి చమురు సరఫ...
30  ఇటీవల అంతర్జాతీయంగా, దేశీయంగా కాస్త నెమ్మదించి...
31  ‘విటమిన్‌ ఏ పాల్మిటేట్‌’ దిగుమతులపై  కేంద్ర వా...
32  అవసరానికి అప్పు తీసుకోవాలంటే.. ఒకప్పుడు ఎన్నో ...
33  Gold and Silver Prices: తెలుగు రాష్ట్రాల్లోని ...
34  Urban Company: హోమ్‌ సర్వీసులు అందించే అర్బన్‌...

In [7]:
df

                                          Description
0                                                 N/A
1                                                 N/A
2                                                 N/A
3                                                 N/A
4                                                 N/A
5                                                 N/A
6                                                 N/A
7                                                 N/A
8                                                 N/A
9                                                 N/A
10                                                N/A
11                                                N/A
12  ఆర్థిక లక్ష్యాలను సాధించడం ఒక్క రోజులో అయ్యే ప...
13  సొంతిల్లు.. అందరి కల. గృహరుణం వడ్డీ రేట్లు కాస...
14  తల్లిదండ్రులందరూ పిల్లలకు మంచి ఆర్థిక భవిష్యత్...
15  అంతా సాఫీగా సాగిపోతుంది అనుకున్న క్షణంలోనే ఎదో...
16  వచ్చే మూడేళ్లలో (2028 కల్లా) ప్రపంచంలోనే మూడో ...
17  త్వరలోనే పదవీ విరమణ చేయబోతున్నాను. ఇప్పుడు నేన...
18  జెన్‌ ఏఐ (జెనరేటివ్‌ కృత్రిమమేధ)తో మనదేశంలో 20...
19  హెచ్‌డీఎఫ్‌సీ మ్యూచువల్‌ ఫండ్‌ ఒక ఇండెక్స్‌ పథ...
20  దేశీయ స్నాక్స్, మిఠాయిల కంపెనీ హల్దీరామ్‌ స్నా...
21  ఓలా ఎలక్ట్రిక్, హోలీ సందర్భంగా ఫ్లాష్‌ సేల్‌ ప...
22  ఒక కంపెనీ షేరు ధరలను ప్రభావితం చేసే సమాచారం (య...
23  దేశీయంగా ప్రయాణికుల వాహన (కార్లు, ఎస్‌యూవీ, వ్...
24  సూచీలు వరుసగా అయిదో రోజూ నష్టాలపాలయ్యాయి. స్థి...
25  ప్రస్తుత ఆర్థిక సంవత్సరం ఏప్రిల్‌- డిసెంబరులో ...
26  అమెరికా మార్కెట్లో విడుదల చేసిన ఒక ఔషధం బ్యాచ్...
27  పర్యావరణ మార్పు వల్ల జరిగే ప్రమాదాలు, నష్టాలు,...
28  మాగ్మా జనరల్‌ ఇన్సూరెన్స్‌ను బాబా రామ్‌దేవ్‌ న...
29  అమెరికా ఆంక్షల నేపథ్యంలో రష్యా నుంచి చమురు సరఫ...
30  ఇటీవల అంతర్జాతీయంగా, దేశీయంగా కాస్త నెమ్మదించి...
31  ‘విటమిన్‌ ఏ పాల్మిటేట్‌’ దిగుమతులపై  కేంద్ర వా...
32  అవసరానికి అప్పు తీసుకోవాలంటే.. ఒకప్పుడు ఎన్నో ...
33  Gold and Silver Prices: తెలుగు రాష్ట్రాల్లోని ...
34  Urban Company: హోమ్‌ సర్వీసులు అందించే అర్బన్‌...

In [8]:
df = df.drop(df.index[:11])  # Drops rows from index 0 to 9
df = df.reset_index(drop=True)  # Reset index

In [9]:
df

                                          Description
0                                                 N/A
1   ఆర్థిక లక్ష్యాలను సాధించడం ఒక్క రోజులో అయ్యే ప...
2   సొంతిల్లు.. అందరి కల. గృహరుణం వడ్డీ రేట్లు కాస...
3   తల్లిదండ్రులందరూ పిల్లలకు మంచి ఆర్థిక భవిష్యత్...
4   అంతా సాఫీగా సాగిపోతుంది అనుకున్న క్షణంలోనే ఎదో...
5   వచ్చే మూడేళ్లలో (2028 కల్లా) ప్రపంచంలోనే మూడో ...
6   త్వరలోనే పదవీ విరమణ చేయబోతున్నాను. ఇప్పుడు నేన...
7   జెన్‌ ఏఐ (జెనరేటివ్‌ కృత్రిమమేధ)తో మనదేశంలో 20...
8   హెచ్‌డీఎఫ్‌సీ మ్యూచువల్‌ ఫండ్‌ ఒక ఇండెక్స్‌ పథ...
9   దేశీయ స్నాక్స్, మిఠాయిల కంపెనీ హల్దీరామ్‌ స్నా...
10  ఓలా ఎలక్ట్రిక్, హోలీ సందర్భంగా ఫ్లాష్‌ సేల్‌ ప...
11  ఒక కంపెనీ షేరు ధరలను ప్రభావితం చేసే సమాచారం (య...
12  దేశీయంగా ప్రయాణికుల వాహన (కార్లు, ఎస్‌యూవీ, వ్...
13  సూచీలు వరుసగా అయిదో రోజూ నష్టాలపాలయ్యాయి. స్థి...
14  ప్రస్తుత ఆర్థిక సంవత్సరం ఏప్రిల్‌- డిసెంబరులో ...
15  అమెరికా మార్కెట్లో విడుదల చేసిన ఒక ఔషధం బ్యాచ్...
16  పర్యావరణ మార్పు వల్ల జరిగే ప్రమాదాలు, నష్టాలు,...
17  మాగ్మా జనరల్‌ ఇన్సూరెన్స్‌ను బాబా రామ్‌దేవ్‌ న...
18  అమెరికా ఆంక్షల నేపథ్యంలో రష్యా నుంచి చమురు సరఫ...
19  ఇటీవల అంతర్జాతీయంగా, దేశీయంగా కాస్త నెమ్మదించి...
20  ‘విటమిన్‌ ఏ పాల్మిటేట్‌’ దిగుమతులపై  కేంద్ర వా...
21  అవసరానికి అప్పు తీసుకోవాలంటే.. ఒకప్పుడు ఎన్నో ...
22  Gold and Silver Prices: తెలుగు రాష్ట్రాల్లోని ...
23  Urban Company: హోమ్‌ సర్వీసులు అందించే అర్బన్‌...

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Define the target URL
url = "https://www.eenadu.net/business/latest-news"

# Send a request to fetch the HTML content
response = requests.get(url)
response.raise_for_status()  # Ensure request was successful

# Parse the HTML content
soup = BeautifulSoup(response.text, "html.parser")

# Extract all news articles (links with headlines)
articles = soup.find_all("a", href=True)  # Find all <a> tags with href

# Lists to store data
headlines, links = [], []

# Loop through each article link
for article in articles:
    headline = article.text.strip()  # Get the text inside <a>
    link = article["href"]  # Extract the URL

    if headline and link.startswith("https://www.eenadu.net/telugu-news/business"):  # Filter relevant links
        headlines.append(headline)
        links.append(link)

# Create a DataFrame
df1 = pd.DataFrame({"Headline": headlines, "URL": links})

# Display DataFrame
print(df1)

                                             Headline  \
0   లక్ష్య సాధనకు సూత్రాలివీ ఆర్థిక లక్ష్యాలను సాధ...
1   పిల్లలకు నేర్పిద్దాం ఆర్థిక పాఠాలు తల్లిదండ్రు...
2   ఇల్లు కొంటున్నారా? సొంతిల్లు.. అందరి కల. గృహరు...
3   యాప్‌లలో అప్పు చేస్తుంటే అవసరానికి అప్పు తీసుక...
4   ఫాస్టాగ్‌ 70 నిమిషాల రూల్‌.. NHAI క్లారిటీ New...
..                                                ...
60                         రూ.కోటి పాలసీ తీసుకోవచ్చా?
61       దుబాయ్‌లో ఉంటున్నాను ఫండ్లలో మదుపు చేయొచ్చా?
62                             పాలసీని మార్చుకోవచ్చా?
63                           ఇంటి కోసం పెట్టుబడి ఎలా?
64                           ఈఎల్‌ఎస్‌ఎస్‌లు ఆపేయాలా?

                                                  URL
0   https://www.eenadu.net/telugu-news/business/ge...
1   https://www.eenadu.net/telugu-news/business/le...
2   https://www.eenadu.net/telugu-news/business/pr...
3   https://www.eenadu.net/telugu-news/business/th...
4   https://www.eenadu.net/telugu-news/business/go...
..                                                ...
60  https://www.eenadu.net/telugu-news/business/ge...
61  https://www.eenadu.net/telugu-news/business/ge...
62  https://www.eenadu.net/telugu-news/business/ge...
63  https://www.eenadu.net/telugu-news/business/ge...
64  https://www.eenadu.net/telugu-news/business/ge...

[65 rows x 2 columns]

In [11]:
df1

,Headline,URL
0,లక్ష్య సాధనకు సూత్రాలివీ ఆర్థిక లక్ష్యాలను సాధ...,https://www.eenadu.net/telugu-news/business/ge...
1,పిల్లలకు నేర్పిద్దాం ఆర్థిక పాఠాలు తల్లిదండ్రు...,https://www.eenadu.net/telugu-news/business/le...
2,ఇల్లు కొంటున్నారా? సొంతిల్లు.. అందరి కల. గృహరు...,https://www.eenadu.net/telugu-news/business/pr...
3,యాప్‌లలో అప్పు చేస్తుంటే అవసరానికి అప్పు తీసుక...,https://www.eenadu.net/telugu-news/business/th...
4,ఫాస్టాగ్‌ 70 నిమిషాల రూల్‌.. NHAI క్లారిటీ New...,https://www.eenadu.net/telugu-news/business/go...
...,...,...
60,రూ.కోటి పాలసీ తీసుకోవచ్చా?,https://www.eenadu.net/telugu-news/business/ge...
61,దుబాయ్‌లో ఉంటున్నాను ఫండ్లలో మదుపు చేయొచ్చా?,https://www.eenadu.net/telugu-news/business/ge...
62,పాలసీని మార్చుకోవచ్చా?,https://www.eenadu.net/telugu-news/business/ge...
63,ఇంటి కోసం పెట్టుబడి ఎలా?,https://www.eenadu.net/telugu-news/business/ge...
64,ఈఎల్‌ఎస్‌ఎస్‌లు ఆపేయాలా?,https://www.eenadu.net/telugu-news/business/ge...

In [12]:
df1 = df1.drop(columns=['URL'])
df1

                                             Headline
0   లక్ష్య సాధనకు సూత్రాలివీ ఆర్థిక లక్ష్యాలను సాధ...
1   పిల్లలకు నేర్పిద్దాం ఆర్థిక పాఠాలు తల్లిదండ్రు...
2   ఇల్లు కొంటున్నారా? సొంతిల్లు.. అందరి కల. గృహరు...
3   యాప్‌లలో అప్పు చేస్తుంటే అవసరానికి అప్పు తీసుక...
4   ఫాస్టాగ్‌ 70 నిమిషాల రూల్‌.. NHAI క్లారిటీ New...
..                                                ...
60                         రూ.కోటి పాలసీ తీసుకోవచ్చా?
61       దుబాయ్‌లో ఉంటున్నాను ఫండ్లలో మదుపు చేయొచ్చా?
62                             పాలసీని మార్చుకోవచ్చా?
63                           ఇంటి కోసం పెట్టుబడి ఎలా?
64                           ఈఎల్‌ఎస్‌ఎస్‌లు ఆపేయాలా?

[65 rows x 1 columns]

In [13]:
df = df.rename(columns={'Description': 'Headlines'})
df

                                            Headlines
0                                                 N/A
1   ఆర్థిక లక్ష్యాలను సాధించడం ఒక్క రోజులో అయ్యే ప...
2   సొంతిల్లు.. అందరి కల. గృహరుణం వడ్డీ రేట్లు కాస...
3   తల్లిదండ్రులందరూ పిల్లలకు మంచి ఆర్థిక భవిష్యత్...
4   అంతా సాఫీగా సాగిపోతుంది అనుకున్న క్షణంలోనే ఎదో...
5   వచ్చే మూడేళ్లలో (2028 కల్లా) ప్రపంచంలోనే మూడో ...
6   త్వరలోనే పదవీ విరమణ చేయబోతున్నాను. ఇప్పుడు నేన...
7   జెన్‌ ఏఐ (జెనరేటివ్‌ కృత్రిమమేధ)తో మనదేశంలో 20...
8   హెచ్‌డీఎఫ్‌సీ మ్యూచువల్‌ ఫండ్‌ ఒక ఇండెక్స్‌ పథ...
9   దేశీయ స్నాక్స్, మిఠాయిల కంపెనీ హల్దీరామ్‌ స్నా...
10  ఓలా ఎలక్ట్రిక్, హోలీ సందర్భంగా ఫ్లాష్‌ సేల్‌ ప...
11  ఒక కంపెనీ షేరు ధరలను ప్రభావితం చేసే సమాచారం (య...
12  దేశీయంగా ప్రయాణికుల వాహన (కార్లు, ఎస్‌యూవీ, వ్...
13  సూచీలు వరుసగా అయిదో రోజూ నష్టాలపాలయ్యాయి. స్థి...
14  ప్రస్తుత ఆర్థిక సంవత్సరం ఏప్రిల్‌- డిసెంబరులో ...
15  అమెరికా మార్కెట్లో విడుదల చేసిన ఒక ఔషధం బ్యాచ్...
16  పర్యావరణ మార్పు వల్ల జరిగే ప్రమాదాలు, నష్టాలు,...
17  మాగ్మా జనరల్‌ ఇన్సూరెన్స్‌ను బాబా రామ్‌దేవ్‌ న...
18  అమెరికా ఆంక్షల నేపథ్యంలో రష్యా నుంచి చమురు సరఫ...
19  ఇటీవల అంతర్జాతీయంగా, దేశీయంగా కాస్త నెమ్మదించి...
20  ‘విటమిన్‌ ఏ పాల్మిటేట్‌’ దిగుమతులపై  కేంద్ర వా...
21  అవసరానికి అప్పు తీసుకోవాలంటే.. ఒకప్పుడు ఎన్నో ...
22  Gold and Silver Prices: తెలుగు రాష్ట్రాల్లోని ...
23  Urban Company: హోమ్‌ సర్వీసులు అందించే అర్బన్‌...

In [14]:
df1 = df1.rename(columns={'Headline': 'Headlines'})
df1

                                            Headlines
0   లక్ష్య సాధనకు సూత్రాలివీ ఆర్థిక లక్ష్యాలను సాధ...
1   పిల్లలకు నేర్పిద్దాం ఆర్థిక పాఠాలు తల్లిదండ్రు...
2   ఇల్లు కొంటున్నారా? సొంతిల్లు.. అందరి కల. గృహరు...
3   యాప్‌లలో అప్పు చేస్తుంటే అవసరానికి అప్పు తీసుక...
4   ఫాస్టాగ్‌ 70 నిమిషాల రూల్‌.. NHAI క్లారిటీ New...
..                                                ...
60                         రూ.కోటి పాలసీ తీసుకోవచ్చా?
61       దుబాయ్‌లో ఉంటున్నాను ఫండ్లలో మదుపు చేయొచ్చా?
62                             పాలసీని మార్చుకోవచ్చా?
63                           ఇంటి కోసం పెట్టుబడి ఎలా?
64                           ఈఎల్‌ఎస్‌ఎస్‌లు ఆపేయాలా?

[65 rows x 1 columns]

In [15]:
df_combined = pd.concat([df, df1], ignore_index=True)

# Ensure the column name remains "Headlines"
df_combined.columns = ["Headlines"]

In [16]:
df_combined

                                            Headlines
0                                                 N/A
1   ఆర్థిక లక్ష్యాలను సాధించడం ఒక్క రోజులో అయ్యే ప...
2   సొంతిల్లు.. అందరి కల. గృహరుణం వడ్డీ రేట్లు కాస...
3   తల్లిదండ్రులందరూ పిల్లలకు మంచి ఆర్థిక భవిష్యత్...
4   అంతా సాఫీగా సాగిపోతుంది అనుకున్న క్షణంలోనే ఎదో...
..                                                ...
84                         రూ.కోటి పాలసీ తీసుకోవచ్చా?
85       దుబాయ్‌లో ఉంటున్నాను ఫండ్లలో మదుపు చేయొచ్చా?
86                             పాలసీని మార్చుకోవచ్చా?
87                           ఇంటి కోసం పెట్టుబడి ఎలా?
88                           ఈఎల్‌ఎస్‌ఎస్‌లు ఆపేయాలా?

[89 rows x 1 columns]

In [17]:
# Define the filename
csv_filename = "telugu_business_news.csv"

# Save DataFrame to CSV file
df_combined.to_csv(csv_filename, index=False, encoding="utf-8-sig")

print(f"Data saved successfully to {csv_filename}")

Data saved successfully to telugu_business_news.csv